### ISSUE TITLE
throwable consumables like candle, torch, dynamite, and bombs

### ISSUE THREAD

**Issue by Mooses2k** [Mooses2k/SecretHistories#18]
make equippable item category: consumable

candle 1.5m radius, torch 9m radius

10m throw reasonable distance flat, maybe more if highly arced
* rock/brick, throwable, stack of 3
* 1.25" x 8" dynamite stick is standard - offensive grenade - 5m radius, deadly
* 6lb black powder cannonball with 5s fuse - defensive grenade, 10m blast radius, deadly or disabling
* NOT a firebomb aka Molotov right now (requires fire, so much more work)

create blastwave version of this: http://www.iforce2d.net/b2dtut/explosions

**Comment by Mooses2k** [comment]
have basic candle

**Comment by Mooses2k** [comment]
basic bomb made, no timer, no trigger
explosion implemented from tut

**Comment by Mooses2k** [comment]
rock, candle, torch implemented. Waiting on Ayo to implement the dyaniate and grenade (art uploaded)

**Comment by Mooses2k** [comment]
Everything done except sound and blast damage effect: http://www.iforce2d.net/b2dtut/explosions

**Comment by Mooses2k** [comment]
Ayo's going to do the raycast sphere thing.

Some docs:
https://github.com/godotengine/godot/issues/2217
https://github.com/V-Sekai/godot-shape-cast

**Comment by Ayomideabdulazeez** [comment]
So the after effects of the explosion that is the shockwave and any other thing would be improved using the shapecast node in Godot 4 but the shapecast logic is temporarily unavailable for now, would be using this when the game is ported to Godot 4

**Comment by Mooses2k** [comment]
Ayo has demonstrated a decent scene-raycast sphere system that's okay but lags the game a bit. Good enough for demo. Waiting for damage on raycasts then will merge.
