### ISSUE TITLE
red screen flash on hit & dark blood/retinal capillaries from edges of screen

### ISSUE THREAD

**Issue by Mooses2k** [Mooses2k/SecretHistories#20]
red screen flash when hit, shrunken area of vision when below 25%, like oval-shaped letterboxing of the screen.

 have dark blood or retinal capillaries or things swimming in from edges of screen for sanity affects.

**Comment by Mooses2k** [comment]
Chris should do:
Well, there's some art need, such as the red capillaries showing at the screen edge when hurt. And stamina and sprinting aren't implemented yet.
And would have to find audio for the heavy breathing.

**Comment by AlekTheSixth** [comment]
Going to do:

- [ ]  Luck meter;
- [ ]  Stamina bar;
- [ ]  Screen red flashes for hits and etc...;
- [ ]  Auto-hiding system; 
- [ ]  Bars.

**Comment by Mooses2k** [comment]
heavy breathing sounds:
https://freesound.org/people/Deathscyp/sounds/553944/
https://freesound.org/people/ceberation/sounds/235519/
https://freesound.org/people/samule44/sounds/96023/

**Comment by Mooses2k** [comment]
> Going to do:
> 
> * [ ]   Luck meter;
> * [ ]   Stamina bar;
> * [ ]   Screen red flashes for hits and etc...;
> * [ ]   Auto-hiding system;
> * [ ]   Bars.

This pretty much not correct. I've adjusted the first entry up top for clarify.

**Comment by Mooses2k** [comment]
Stewie fixed hitboxes. I need to find a red capillary image.

**Comment by Mooses2k** [comment]
Closed with PR #226
