### ISSUE TITLE
initial loot

### ISSUE THREAD

**Issue by Mooses2k** [Mooses2k/SecretHistories#406]
for quick demo item drops (later will be fancier by room purpose and placement anchors
* make list of res links to loot wanted in demo
* for each, weight of selection bias (50 and 1 mean means 50 gets selected 50 times more than 1)
* min and max number found at this spot, random
* randomly choose a room cell (not corridor, if easy enough to do)
* offset in a random horizontal direction so it doesn't sit dead center on the tile
* do a radius check to see if anything else occupies that space, if so, try moving it up an amount
* place item
* iterate n number of times to sparsely fill the level

Overall weight per cell unknown, we'll have to tweak. 1-5% maybe. Strongly prefer rooms to corridors for placing loot, like 10x more likely or so.

The list:
* candle, 1000, 1
* torch, 250, 1
* candlestick, 100, 1
* candelabra, 50, 1
* candle lantern, 25, 1
* oil lantern, 10, 1
* bullseye lantern, 5, 1
* Webley, 5, 1
* Webley ammo box, 5, 1
* Webley loose ammo, 50, 1-5
* Sawed-off shotgun, 10, 1
* Double-barrel shotgun, 20, 1
* 12-gauge ammo box, 5, 1
* 12-gauge loose ammo, 20, 1-5
* Martini-Henry rifle, 20, 1
* Sawed-off Martini-Henry, 1, 1
* Martini-Henry ammo box, 5, 1
* Martini-Henry loose ammo, 20, 1-5
* any melee weapons that are ready, ~40, 1
* dynamite, 5, 1
* grenade, 1, 1

**Comment by eh-jogos** [comment]
Could not find scenes for these items:
- 12-gauge loose ammo, 20, 1-5
- Sawed-off Martini-Henry, 1, 1

Also, which melee weapon is ready? so that I can fill in: "any melee weapons that are ready, ~40, 1"

**Comment by Mooses2k** [comment]
We can leave both of those off, they were shotgun_shell and Khyber Pass Martini. No melee left. I'll leave this open as I'll be removing loose ammo from the initial spawn.

**Comment by Mooses2k** [comment]
eh-jogos, the 'loot spawner' should use the World Seed for randomization.
