### ISSUE TITLE
Spawning Sarcofagos and Fountains as well as making a base for adding purpose to rooms

### ISSUE THREAD

**Issue by eh-jogos** [Mooses2k/SecretHistories#471]
Here are my ideas to handling this task.
## Room Purposes
- change generate rooms to categorize all rooms as "empty" instead of "generic", besides the starting room
- after all other steps that define doors, corridors, and pillars, add a step to "categorize" rooms
- create a generic resource for `RoomPurpose`, that would take a `purpose_id` string and an array of scripts of `RoomRequirements` (Resources), and a max amount of rooms of that purpose per level (or no limit with -1)
  - the `RoomPurpose` resource would have a public method, something like `is_compatible(room_data: RoomData) -> bool` so that we can throw some room data in it and see if its a valid candidate for that purpose. 
  - then we could save a "sarcofagos.tres" resource which would use a `MinSizeRequirement`, possibly a `MaxSizeRequirement` and a `PillarsRequirement`
    - min 2x2 tiles rooms (3mx3m)
    - max ?
    - no pillar rooms
  - fountains.tres  would use the "MinSize" and "Pillars" requirements but not "MaxSize" (or it could use max size as well)
    - min 6x6 tiles room (9mx9m)
    - no pillars as well I guess?
- The "Categorize" Step 
   - would have an export var for an array of `RoomPurpose` files, and for each purpose file it would see between the "empty" rooms which ones are valid for that purpose
  - Then if they have more valid rooms then allowed, we would just randomly choose between them until the quota is filled
  - If there are less valid rooms or there are no limits for that "purpose" then all compatible rooms become of that purpose and exit the pool for the next purpose check
  - With that, the order of the array would also indicate the "priority" for the purposes
  - For now the only purposes would be "empty", "sarcofagos" and "fountain", with "starting_room" keeping as a special "purpose" that is excluded from all this.

This way it would be easy to change the purposes at any time, and later improve this base system so that rooms can have original and current purposes by adding another step for the "OriginalPurpose", which would take all rooms, regardless of "current purpose" and check what "old purpose" is compatible with it. 

The only "problem" is that exporting custom resources to the editor in Godot 3.x is clumsy, but on Godot 4.x this approach works very nicely and everything is easily "tweakable" in the editor, without having to change code.

## Handling Sarcophagus and Fountain
- There could then be later steps on world Generation for each type of room, so a "HandleSarcophagusRooms" step for example
  - this one would get the list of rooms with "sarcophagus" purpose, and do everything it needs like:
      - check which walls have doors and which doesn't
      - create data for later spawning sarcophagus on the walls that don't have doors, according to the wall size
      - create data for later spawning spawn sarcophagus in the middle if the rooms is big enough
  - same thing for the fountain

Then the `spawn_items.gd` would take care of spawning all the "non character" spawn data generated in the world generation, like its already doing, without having to change anything on it

**Comment by Mooses2k** [comment]
This is great.

Here's the only adjustments:
Sarcophagus rooms should be called 'crypt', fountain rooms should be called 'fountain_room'. Starting room, we can call 'level_staircase' if you want or change that when we do staircases, next.

Pillars allowed for fountain rooms.

You mentioned that this is a bit annoying with Godot 3.5. Easy enough for our small set of demo rooms, though, right?

**Comment by eh-jogos** [comment]
> You mentioned that this is a bit annoying with Godot 3.5. Easy enough for our small set of demo rooms, though, right?

yes, the "annoying" part is having to choose the resources from a list of "ALL" available resource on the editor, since you can't really export custom resources directly, and maybe some type casting on the code.

**Comment by eh-jogos** [comment]
this was closed by PR #482
