### ISSUE TITLE
Fix worldgen regressions after recent staircase work

### ISSUE THREAD

**Issue by Mooses2k** [Mooses2k/SecretHistories#536]
BUGFIX:
* Seed 7917 has a crash "Invalid get index '3' (on base: 'Dictionary')." line 9 in procedural_world.gd in function get_player_spawn_position()
* wow I'm on a roll! Very next load of game: try seed 47725 and see if you see anything wrong 🙂 (had another seed do this too) 
* related again to world gen, check seed 43693. Exit stairwell, turn all rights until you end up seeing the backside of a stairwell seen through an open doorway. That's undesirable behavior.
* -31231 creates another degenerate world. two stairways, a single room, and corridors connecting them. This gen mentions it makes a character, but that cultist is not accessible (and just one room is bogus, of course) (had another seed do similar, one room, nothing else) 
* 🙂 Seed 50533 spawns a cultist between a wall and a sarco and he's glitching his falling animation over and over. Don't spawn them in sarcos either, obviously.
* This one's fun. Seed -5265

**Comment by eh-jogos** [comment]
Please separate things that are not a bug into a new issue, or multiple new issues.
